name: NovaSkywars
main: net.novauniverse.games.skywars.NovaSkywars
description: Novauniverse Skywars
version: 1.0
depend: [NovaCore, NovaCoreGameEngine]
softdepend: [NovaGamesTarget]

authors: [Zeeraa, NovaUniverse]